# Generated by Django 3.1.2 on 2020-12-07 14:41

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('credit_hours', models.IntegerField()),
                ('decription', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('cnic', models.IntegerField(unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
