# Generated by Django 3.1.2 on 2020-12-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
