# Generated by Django 3.1.2 on 2020-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201218_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='markeditem',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='markeditem',
            name='weightage',
            field=models.FloatField(),
        ),
    ]
