# Generated by Django 3.1.2 on 2022-05-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_id',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
