# Generated by Django 3.1.2 on 2022-05-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220524_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
